# Generated by Django 3.0 on 2021-02-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('column_separator', models.CharField(choices=[(',', ','), (';', ';')], max_length=10)),
                ('columns', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready')], max_length=30)),
                ('csv_file', models.FileField(upload_to='documents')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='schemas.Schema')),
            ],
        ),
    ]
