# Generated by Django 3.0 on 2021-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='columns',
            field=models.CharField(max_length=255),
        ),
    ]
