# Generated by Django 3.0 on 2021-02-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20210204_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='csv_file',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
