# Generated by Django 3.0 on 2021-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20210204_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
